// ============================================================================
//
// Copyright (c) 2006-2015, Talend Inc.
//
// This source code has been automatically generated by_Talend Open Studio for Data Integration
// / Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.


package completo.xchange_api_consume_0_1;

import routines.Numeric;
import routines.DataOperation;
import routines.TalendDataGenerator;
import routines.TalendStringUtil;
import routines.TalendString;
import routines.StringHandling;
import routines.Relational;
import routines.TalendDate;
import routines.Mathematical;
import routines.routineFecha;
import routines.system.*;
import routines.system.api.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.math.BigDecimal;
import java.io.ByteArrayOutputStream;
import java.io.ByteArrayInputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.ObjectOutputStream;
import java.io.ObjectInputStream;
import java.io.IOException;
import java.util.Comparator;
 





@SuppressWarnings("unused")

/**
 * Job: xchange_api_consume Purpose: <br>
 * Description:  <br>
 * @author user@talend.com
 * @version 7.0.1.20180411_1414
 * @status 
 */
public class xchange_api_consume implements TalendJob {

protected static void logIgnoredError(String message, Throwable cause) {
       System.err.println(message);
       if (cause != null) {
               cause.printStackTrace();
       }

}


	public final Object obj = new Object();

	// for transmiting parameters purpose
	private Object valueObject = null;

	public Object getValueObject() {
		return this.valueObject;
	}

	public void setValueObject(Object valueObject) {
		this.valueObject = valueObject;
	}
	
	private final static String defaultCharset = java.nio.charset.Charset.defaultCharset().name();

	
	private final static String utf8Charset = "UTF-8";
	//contains type for every context property
	public class PropertiesWithType extends java.util.Properties {
		private static final long serialVersionUID = 1L;
		private java.util.Map<String,String> propertyTypes = new java.util.HashMap<>();
		
		public PropertiesWithType(java.util.Properties properties){
			super(properties);
		}
		public PropertiesWithType(){
			super();
		}
		
		public void setContextType(String key, String type) {
			propertyTypes.put(key,type);
		}
	
		public String getContextType(String key) {
			return propertyTypes.get(key);
		}
	}
	
	// create and load default properties
	private java.util.Properties defaultProps = new java.util.Properties();
	// create application properties with default
	public class ContextProperties extends PropertiesWithType {

		private static final long serialVersionUID = 1L;

		public ContextProperties(java.util.Properties properties){
			super(properties);
		}
		public ContextProperties(){
			super();
		}

		public void synchronizeContext(){
			
		}

	}
	private ContextProperties context = new ContextProperties();
	public ContextProperties getContext() {
		return this.context;
	}
	private final String jobVersion = "0.1";
	private final String jobName = "xchange_api_consume";
	private final String projectName = "COMPLETO";
	public Integer errorCode = null;
	private String currentComponent = "";
	
		private final java.util.Map<String, Object> globalMap = new java.util.HashMap<String, Object>();
        private final static java.util.Map<String, Object> junitGlobalMap = new java.util.HashMap<String, Object>();
	
		private final java.util.Map<String, Long> start_Hash = new java.util.HashMap<String, Long>();
		private final java.util.Map<String, Long> end_Hash = new java.util.HashMap<String, Long>();
		private final java.util.Map<String, Boolean> ok_Hash = new java.util.HashMap<String, Boolean>();
		public  final java.util.List<String[]> globalBuffer = new java.util.ArrayList<String[]>();
	

private RunStat runStat = new RunStat();

	// OSGi DataSource
	private final static String KEY_DB_DATASOURCES = "KEY_DB_DATASOURCES";
	
	private final static String KEY_DB_DATASOURCES_RAW = "KEY_DB_DATASOURCES_RAW";

	public void setDataSources(java.util.Map<String, javax.sql.DataSource> dataSources) {
		java.util.Map<String, routines.system.TalendDataSource> talendDataSources = new java.util.HashMap<String, routines.system.TalendDataSource>();
		for (java.util.Map.Entry<String, javax.sql.DataSource> dataSourceEntry : dataSources.entrySet()) {
			talendDataSources.put(dataSourceEntry.getKey(), new routines.system.TalendDataSource(dataSourceEntry.getValue()));
		}
		globalMap.put(KEY_DB_DATASOURCES, talendDataSources);
		globalMap.put(KEY_DB_DATASOURCES_RAW, new java.util.HashMap<String, javax.sql.DataSource>(dataSources));
	}


private final java.io.ByteArrayOutputStream baos = new java.io.ByteArrayOutputStream();
private final java.io.PrintStream errorMessagePS = new java.io.PrintStream(new java.io.BufferedOutputStream(baos));

public String getExceptionStackTrace() {
	if ("failure".equals(this.getStatus())) {
		errorMessagePS.flush();
		return baos.toString();
	}
	return null;
}

private Exception exception;

public Exception getException() {
	if ("failure".equals(this.getStatus())) {
		return this.exception;
	}
	return null;
}

private class TalendException extends Exception {

	private static final long serialVersionUID = 1L;

	private java.util.Map<String, Object> globalMap = null;
	private Exception e = null;
	private String currentComponent = null;
	private String virtualComponentName = null;
	
	public void setVirtualComponentName (String virtualComponentName){
		this.virtualComponentName = virtualComponentName;
	}

	private TalendException(Exception e, String errorComponent, final java.util.Map<String, Object> globalMap) {
		this.currentComponent= errorComponent;
		this.globalMap = globalMap;
		this.e = e;
	}

	public Exception getException() {
		return this.e;
	}

	public String getCurrentComponent() {
		return this.currentComponent;
	}

	
    public String getExceptionCauseMessage(Exception e){
        Throwable cause = e;
        String message = null;
        int i = 10;
        while (null != cause && 0 < i--) {
            message = cause.getMessage();
            if (null == message) {
                cause = cause.getCause();
            } else {
                break;          
            }
        }
        if (null == message) {
            message = e.getClass().getName();
        }   
        return message;
    }

	@Override
	public void printStackTrace() {
		if (!(e instanceof TalendException || e instanceof TDieException)) {
			if(virtualComponentName!=null && currentComponent.indexOf(virtualComponentName+"_")==0){
				globalMap.put(virtualComponentName+"_ERROR_MESSAGE",getExceptionCauseMessage(e));
			}
			globalMap.put(currentComponent+"_ERROR_MESSAGE",getExceptionCauseMessage(e));
			System.err.println("Exception in component " + currentComponent + " (" + jobName + ")");
		}
		if (!(e instanceof TDieException)) {
			if(e instanceof TalendException){
				e.printStackTrace();
			} else {
				e.printStackTrace();
				e.printStackTrace(errorMessagePS);
				xchange_api_consume.this.exception = e;
			}
		}
		if (!(e instanceof TalendException)) {
		try {
			for (java.lang.reflect.Method m : this.getClass().getEnclosingClass().getMethods()) {
				if (m.getName().compareTo(currentComponent + "_error") == 0) {
					m.invoke(xchange_api_consume.this, new Object[] { e , currentComponent, globalMap});
					break;
				}
			}

			if(!(e instanceof TDieException)){
			}
		} catch (Exception e) {
			this.e.printStackTrace();
		}
		}
	}
}

			public void tRESTClient_2_error(Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap) throws TalendException {
				
				end_Hash.put(errorComponent, System.currentTimeMillis());
				
				status = "failure";
				
					tRESTClient_2_onSubJobError(exception, errorComponent, globalMap);
			}
			
			public void tExtractXMLField_1_error(Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap) throws TalendException {
				
				end_Hash.put(errorComponent, System.currentTimeMillis());
				
				status = "failure";
				
					tRESTClient_2_onSubJobError(exception, errorComponent, globalMap);
			}
			
			public void tXMLMap_1_error(Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap) throws TalendException {
				
				end_Hash.put(errorComponent, System.currentTimeMillis());
				
				status = "failure";
				
					tRESTClient_2_onSubJobError(exception, errorComponent, globalMap);
			}
			
			public void tMysqlOutput_2_error(Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap) throws TalendException {
				
				end_Hash.put(errorComponent, System.currentTimeMillis());
				
				status = "failure";
				
					tRESTClient_2_onSubJobError(exception, errorComponent, globalMap);
			}
			
			public void tRESTClient_2_onSubJobError(Exception exception, String errorComponent, final java.util.Map<String, Object> globalMap) throws TalendException {

resumeUtil.addLog("SYSTEM_LOG", "NODE:"+ errorComponent, "", Thread.currentThread().getId()+ "", "FATAL", "", exception.getMessage(), ResumeUtil.getExceptionStackTrace(exception),"");

			}
		






public static class insertsStruct implements routines.system.IPersistableRow<insertsStruct> {
    final static byte[] commonByteArrayLock_COMPLETO_xchange_api_consume = new byte[0];
    static byte[] commonByteArray_COMPLETO_xchange_api_consume = new byte[0];

	
			    public String name;

				public String getName () {
					return this.name;
				}
				
			    public Double exchange;

				public Double getExchange () {
					return this.exchange;
				}
				
			    public String date;

				public String getDate () {
					return this.date;
				}
				
			    public String currency1;

				public String getCurrency1 () {
					return this.currency1;
				}
				
			    public String currency2;

				public String getCurrency2 () {
					return this.currency2;
				}
				



	private String readString(ObjectInputStream dis) throws IOException{
		String strReturn = null;
		int length = 0;
        length = dis.readInt();
		if (length == -1) {
			strReturn = null;
		} else {
			if(length > commonByteArray_COMPLETO_xchange_api_consume.length) {
				if(length < 1024 && commonByteArray_COMPLETO_xchange_api_consume.length == 0) {
   					commonByteArray_COMPLETO_xchange_api_consume = new byte[1024];
				} else {
   					commonByteArray_COMPLETO_xchange_api_consume = new byte[2 * length];
   				}
			}
			dis.readFully(commonByteArray_COMPLETO_xchange_api_consume, 0, length);
			strReturn = new String(commonByteArray_COMPLETO_xchange_api_consume, 0, length, utf8Charset);
		}
		return strReturn;
	}

    private void writeString(String str, ObjectOutputStream dos) throws IOException{
		if(str == null) {
            dos.writeInt(-1);
		} else {
            byte[] byteArray = str.getBytes(utf8Charset);
	    	dos.writeInt(byteArray.length);
			dos.write(byteArray);
    	}
    }

    public void readData(ObjectInputStream dis) {

		synchronized(commonByteArrayLock_COMPLETO_xchange_api_consume) {

        	try {

        		int length = 0;
		
					this.name = readString(dis);
					
			            length = dis.readByte();
           				if (length == -1) {
           	    			this.exchange = null;
           				} else {
           			    	this.exchange = dis.readDouble();
           				}
					
					this.date = readString(dis);
					
					this.currency1 = readString(dis);
					
					this.currency2 = readString(dis);
					
        	} catch (IOException e) {
	            throw new RuntimeException(e);

		

        }

		

      }


    }

    public void writeData(ObjectOutputStream dos) {
        try {

		
					// String
				
						writeString(this.name,dos);
					
					// Double
				
						if(this.exchange == null) {
			                dos.writeByte(-1);
						} else {
               				dos.writeByte(0);
           			    	dos.writeDouble(this.exchange);
		            	}
					
					// String
				
						writeString(this.date,dos);
					
					// String
				
						writeString(this.currency1,dos);
					
					// String
				
						writeString(this.currency2,dos);
					
        	} catch (IOException e) {
	            throw new RuntimeException(e);
        }


    }


    public String toString() {

		StringBuilder sb = new StringBuilder();
		sb.append(super.toString());
		sb.append("[");
		sb.append("name="+name);
		sb.append(",exchange="+String.valueOf(exchange));
		sb.append(",date="+date);
		sb.append(",currency1="+currency1);
		sb.append(",currency2="+currency2);
	    sb.append("]");

	    return sb.toString();
    }

    /**
     * Compare keys
     */
    public int compareTo(insertsStruct other) {

		int returnValue = -1;
		
	    return returnValue;
    }


    private int checkNullsAndCompare(Object object1, Object object2) {
        int returnValue = 0;
		if (object1 instanceof Comparable && object2 instanceof Comparable) {
            returnValue = ((Comparable) object1).compareTo(object2);
        } else if (object1 != null && object2 != null) {
            returnValue = compareStrings(object1.toString(), object2.toString());
        } else if (object1 == null && object2 != null) {
            returnValue = 1;
        } else if (object1 != null && object2 == null) {
            returnValue = -1;
        } else {
            returnValue = 0;
        }

        return returnValue;
    }

    private int compareStrings(String string1, String string2) {
        return string1.compareTo(string2);
    }


}

public static class row2Struct implements routines.system.IPersistableRow<row2Struct> {
    final static byte[] commonByteArrayLock_COMPLETO_xchange_api_consume = new byte[0];
    static byte[] commonByteArray_COMPLETO_xchange_api_consume = new byte[0];

	
			    public String name;

				public String getName () {
					return this.name;
				}
				
			    public Double exchange;

				public Double getExchange () {
					return this.exchange;
				}
				
			    public Long date;

				public Long getDate () {
					return this.date;
				}
				



	private String readString(ObjectInputStream dis) throws IOException{
		String strReturn = null;
		int length = 0;
        length = dis.readInt();
		if (length == -1) {
			strReturn = null;
		} else {
			if(length > commonByteArray_COMPLETO_xchange_api_consume.length) {
				if(length < 1024 && commonByteArray_COMPLETO_xchange_api_consume.length == 0) {
   					commonByteArray_COMPLETO_xchange_api_consume = new byte[1024];
				} else {
   					commonByteArray_COMPLETO_xchange_api_consume = new byte[2 * length];
   				}
			}
			dis.readFully(commonByteArray_COMPLETO_xchange_api_consume, 0, length);
			strReturn = new String(commonByteArray_COMPLETO_xchange_api_consume, 0, length, utf8Charset);
		}
		return strReturn;
	}

    private void writeString(String str, ObjectOutputStream dos) throws IOException{
		if(str == null) {
            dos.writeInt(-1);
		} else {
            byte[] byteArray = str.getBytes(utf8Charset);
	    	dos.writeInt(byteArray.length);
			dos.write(byteArray);
    	}
    }

    public void readData(ObjectInputStream dis) {

		synchronized(commonByteArrayLock_COMPLETO_xchange_api_consume) {

        	try {

        		int length = 0;
		
					this.name = readString(dis);
					
			            length = dis.readByte();
           				if (length == -1) {
           	    			this.exchange = null;
           				} else {
           			    	this.exchange = dis.readDouble();
           				}
					
			            length = dis.readByte();
           				if (length == -1) {
           	    			this.date = null;
           				} else {
           			    	this.date = dis.readLong();
           				}
					
        	} catch (IOException e) {
	            throw new RuntimeException(e);

		

        }

		

      }


    }

    public void writeData(ObjectOutputStream dos) {
        try {

		
					// String
				
						writeString(this.name,dos);
					
					// Double
				
						if(this.exchange == null) {
			                dos.writeByte(-1);
						} else {
               				dos.writeByte(0);
           			    	dos.writeDouble(this.exchange);
		            	}
					
					// Long
				
						if(this.date == null) {
			                dos.writeByte(-1);
						} else {
               				dos.writeByte(0);
           			    	dos.writeLong(this.date);
		            	}
					
        	} catch (IOException e) {
	            throw new RuntimeException(e);
        }


    }


    public String toString() {

		StringBuilder sb = new StringBuilder();
		sb.append(super.toString());
		sb.append("[");
		sb.append("name="+name);
		sb.append(",exchange="+String.valueOf(exchange));
		sb.append(",date="+String.valueOf(date));
	    sb.append("]");

	    return sb.toString();
    }

    /**
     * Compare keys
     */
    public int compareTo(row2Struct other) {

		int returnValue = -1;
		
	    return returnValue;
    }


    private int checkNullsAndCompare(Object object1, Object object2) {
        int returnValue = 0;
		if (object1 instanceof Comparable && object2 instanceof Comparable) {
            returnValue = ((Comparable) object1).compareTo(object2);
        } else if (object1 != null && object2 != null) {
            returnValue = compareStrings(object1.toString(), object2.toString());
        } else if (object1 == null && object2 != null) {
            returnValue = 1;
        } else if (object1 != null && object2 == null) {
            returnValue = -1;
        } else {
            returnValue = 0;
        }

        return returnValue;
    }

    private int compareStrings(String string1, String string2) {
        return string1.compareTo(string2);
    }


}

public static class row1Struct implements routines.system.IPersistableRow<row1Struct> {
    final static byte[] commonByteArrayLock_COMPLETO_xchange_api_consume = new byte[0];
    static byte[] commonByteArray_COMPLETO_xchange_api_consume = new byte[0];

	
			    public Integer statusCode;

				public Integer getStatusCode () {
					return this.statusCode;
				}
				
			    public routines.system.Document body;

				public routines.system.Document getBody () {
					return this.body;
				}
				
			    public String string;

				public String getString () {
					return this.string;
				}
				


	private Integer readInteger(ObjectInputStream dis) throws IOException{
		Integer intReturn;
        int length = 0;
        length = dis.readByte();
		if (length == -1) {
			intReturn = null;
		} else {
	    	intReturn = dis.readInt();
		}
		return intReturn;
	}

	private void writeInteger(Integer intNum, ObjectOutputStream dos) throws IOException{
		if(intNum == null) {
            dos.writeByte(-1);
		} else {
			dos.writeByte(0);
	    	dos.writeInt(intNum);
    	}
	}

	private String readString(ObjectInputStream dis) throws IOException{
		String strReturn = null;
		int length = 0;
        length = dis.readInt();
		if (length == -1) {
			strReturn = null;
		} else {
			if(length > commonByteArray_COMPLETO_xchange_api_consume.length) {
				if(length < 1024 && commonByteArray_COMPLETO_xchange_api_consume.length == 0) {
   					commonByteArray_COMPLETO_xchange_api_consume = new byte[1024];
				} else {
   					commonByteArray_COMPLETO_xchange_api_consume = new byte[2 * length];
   				}
			}
			dis.readFully(commonByteArray_COMPLETO_xchange_api_consume, 0, length);
			strReturn = new String(commonByteArray_COMPLETO_xchange_api_consume, 0, length, utf8Charset);
		}
		return strReturn;
	}

    private void writeString(String str, ObjectOutputStream dos) throws IOException{
		if(str == null) {
            dos.writeInt(-1);
		} else {
            byte[] byteArray = str.getBytes(utf8Charset);
	    	dos.writeInt(byteArray.length);
			dos.write(byteArray);
    	}
    }

    public void readData(ObjectInputStream dis) {

		synchronized(commonByteArrayLock_COMPLETO_xchange_api_consume) {

        	try {

        		int length = 0;
		
						this.statusCode = readInteger(dis);
					
						this.body = (routines.system.Document) dis.readObject();
					
					this.string = readString(dis);
					
        	} catch (IOException e) {
	            throw new RuntimeException(e);

		
			} catch(ClassNotFoundException eCNFE) {
				 throw new RuntimeException(eCNFE);
		

        }

		

      }


    }

    public void writeData(ObjectOutputStream dos) {
        try {

		
					// Integer
				
						writeInteger(this.statusCode,dos);
					
					// Document
				
       			    	dos.writeObject(this.body);
					
					// String
				
						writeString(this.string,dos);
					
        	} catch (IOException e) {
	            throw new RuntimeException(e);
        }


    }


    public String toString() {

		StringBuilder sb = new StringBuilder();
		sb.append(super.toString());
		sb.append("[");
		sb.append("statusCode="+String.valueOf(statusCode));
		sb.append(",body="+String.valueOf(body));
		sb.append(",string="+string);
	    sb.append("]");

	    return sb.toString();
    }

    /**
     * Compare keys
     */
    public int compareTo(row1Struct other) {

		int returnValue = -1;
		
	    return returnValue;
    }


    private int checkNullsAndCompare(Object object1, Object object2) {
        int returnValue = 0;
		if (object1 instanceof Comparable && object2 instanceof Comparable) {
            returnValue = ((Comparable) object1).compareTo(object2);
        } else if (object1 != null && object2 != null) {
            returnValue = compareStrings(object1.toString(), object2.toString());
        } else if (object1 == null && object2 != null) {
            returnValue = 1;
        } else if (object1 != null && object2 == null) {
            returnValue = -1;
        } else {
            returnValue = 0;
        }

        return returnValue;
    }

    private int compareStrings(String string1, String string2) {
        return string1.compareTo(string2);
    }


}
public void tRESTClient_2Process(final java.util.Map<String, Object> globalMap) throws TalendException {
	globalMap.put("tRESTClient_2_SUBPROCESS_STATE", 0);

 final boolean execStat = this.execStat;
	
		String iterateId = "";
	
	
	String currentComponent = "";
	java.util.Map<String, Object> resourceMap = new java.util.HashMap<String, Object>();

	try {
			// TDI-39566 avoid throwing an useless Exception
			boolean resumeIt = true;
			if (globalResumeTicket == false && resumeEntryMethodName != null) {
				String currentMethodName = new java.lang.Exception().getStackTrace()[0].getMethodName();
				resumeIt = resumeEntryMethodName.equals(currentMethodName);
			}
			if (resumeIt || globalResumeTicket) { //start the resume
				globalResumeTicket = true;



		row1Struct row1 = new row1Struct();
row2Struct row2 = new row2Struct();
insertsStruct inserts = new insertsStruct();






	
	/**
	 * [tMysqlOutput_2 begin ] start
	 */

	

	
		
		ok_Hash.put("tMysqlOutput_2", false);
		start_Hash.put("tMysqlOutput_2", System.currentTimeMillis());
		
	
	currentComponent="tMysqlOutput_2";

	
			if (execStat) {
				if(resourceMap.get("inIterateVComp") == null){
					
						runStat.updateStatOnConnection("inserts" + iterateId, 0, 0);
					
				}
			} 

		
		int tos_count_tMysqlOutput_2 = 0;
		
    	class BytesLimit65535_tMysqlOutput_2{
    		public void limitLog4jByte() throws Exception{
    			
    		}
    	}
    	
        new BytesLimit65535_tMysqlOutput_2().limitLog4jByte();






int nb_line_tMysqlOutput_2 = 0;
int nb_line_update_tMysqlOutput_2 = 0;
int nb_line_inserted_tMysqlOutput_2 = 0;
int nb_line_deleted_tMysqlOutput_2 = 0;
int nb_line_rejected_tMysqlOutput_2 = 0;

int deletedCount_tMysqlOutput_2=0;
int updatedCount_tMysqlOutput_2=0;
int insertedCount_tMysqlOutput_2=0;

int rejectedCount_tMysqlOutput_2=0;

String tableName_tMysqlOutput_2 = "factmoneda";
boolean whetherReject_tMysqlOutput_2 = false;

java.util.Calendar calendar_tMysqlOutput_2 = java.util.Calendar.getInstance();
calendar_tMysqlOutput_2.set(1, 0, 1, 0, 0, 0);
long year1_tMysqlOutput_2 = calendar_tMysqlOutput_2.getTime().getTime();
calendar_tMysqlOutput_2.set(10000, 0, 1, 0, 0, 0);
long year10000_tMysqlOutput_2 = calendar_tMysqlOutput_2.getTime().getTime();
long date_tMysqlOutput_2;

java.sql.Connection conn_tMysqlOutput_2 = null;
		String dbProperties_tMysqlOutput_2 = "noDatetimeStringSync=true";
		String url_tMysqlOutput_2 = null;
		if(dbProperties_tMysqlOutput_2 == null || dbProperties_tMysqlOutput_2.trim().length() == 0) {
			url_tMysqlOutput_2 = "jdbc:mysql://" + "167.99.147.146" + ":" + "3306" + "/" + "stage" + "?" + "rewriteBatchedStatements=true";
		} else {
			String properties_tMysqlOutput_2 = "noDatetimeStringSync=true";
			if (!properties_tMysqlOutput_2.contains("rewriteBatchedStatements")) {
				properties_tMysqlOutput_2 += "&rewriteBatchedStatements=true";
			}

			url_tMysqlOutput_2 = "jdbc:mysql://" + "167.99.147.146" + ":" + "3306" + "/" + "stage" + "?" + properties_tMysqlOutput_2;
		}
		String driverClass_tMysqlOutput_2 = "org.gjt.mm.mysql.Driver";
		
		String dbUser_tMysqlOutput_2 = "tesis";
		

		 
	final String decryptedPassword_tMysqlOutput_2 = routines.system.PasswordEncryptUtil.decryptPassword("edb6ac47853dddd4f4f7aba1746784ea");

		String dbPwd_tMysqlOutput_2 = decryptedPassword_tMysqlOutput_2;
		java.lang.Class.forName(driverClass_tMysqlOutput_2);
		
		conn_tMysqlOutput_2 = java.sql.DriverManager.getConnection(url_tMysqlOutput_2, dbUser_tMysqlOutput_2, dbPwd_tMysqlOutput_2);
		
	
	resourceMap.put("conn_tMysqlOutput_2", conn_tMysqlOutput_2);
        conn_tMysqlOutput_2.setAutoCommit(false);
        int commitEvery_tMysqlOutput_2 = 10000;
        int commitCounter_tMysqlOutput_2 = 0;

int count_tMysqlOutput_2=0;
    	
                                java.sql.DatabaseMetaData dbMetaData_tMysqlOutput_2 = conn_tMysqlOutput_2.getMetaData();
                                java.sql.ResultSet rsTable_tMysqlOutput_2 = dbMetaData_tMysqlOutput_2.getTables(null, null, null, new String[]{"TABLE"});
                                boolean whetherExist_tMysqlOutput_2 = false;
                                while(rsTable_tMysqlOutput_2.next()) {
                                    String table_tMysqlOutput_2 = rsTable_tMysqlOutput_2.getString("TABLE_NAME");
                                    if(table_tMysqlOutput_2.equalsIgnoreCase("factmoneda")) {
                                        whetherExist_tMysqlOutput_2 = true;
                                        break;
                                    }
                                }
                                rsTable_tMysqlOutput_2.close();
                                if(!whetherExist_tMysqlOutput_2) {
                                    java.sql.Statement stmtCreate_tMysqlOutput_2 = conn_tMysqlOutput_2.createStatement();
                                        stmtCreate_tMysqlOutput_2.execute("CREATE TABLE `" + tableName_tMysqlOutput_2 + "`(`name` VARCHAR(20)  ,`xchange` DOUBLE ,`date` VARCHAR(15)  ,`m1` VARCHAR(5)  ,`m2` VARCHAR(5)  )");
                                    stmtCreate_tMysqlOutput_2.close();
                                }

				String insert_tMysqlOutput_2 = "INSERT INTO `" + "factmoneda" + "` (`name`,`xchange`,`date`,`m1`,`m2`) VALUES (?,?,?,?,?)";
		        int batchSize_tMysqlOutput_2 = 100;
	   			int batchSizeCounter_tMysqlOutput_2=0;
		            
		        java.sql.PreparedStatement pstmt_tMysqlOutput_2 = conn_tMysqlOutput_2.prepareStatement(insert_tMysqlOutput_2);


 



/**
 * [tMysqlOutput_2 begin ] stop
 */



	
	/**
	 * [tXMLMap_1 begin ] start
	 */

	

	
		
		ok_Hash.put("tXMLMap_1", false);
		start_Hash.put("tXMLMap_1", System.currentTimeMillis());
		
	
	currentComponent="tXMLMap_1";

	
			if (execStat) {
				if(resourceMap.get("inIterateVComp") == null){
					
						runStat.updateStatOnConnection("row2" + iterateId, 0, 0);
					
				}
			} 

		
		int tos_count_tXMLMap_1 = 0;
		
    	class BytesLimit65535_tXMLMap_1{
    		public void limitLog4jByte() throws Exception{
    			
    		}
    	}
    	
        new BytesLimit65535_tXMLMap_1().limitLog4jByte();

	
	
//===============================input xml init part===============================
class XML_API_tXMLMap_1{
	public boolean isDefNull(org.dom4j.Node node) throws javax.xml.transform.TransformerException {
        if (node != null && node instanceof org.dom4j.Element) {
        	org.dom4j.Attribute attri = ((org.dom4j.Element)node).attribute("nil");
        	if(attri != null && ("true").equals(attri.getText())){
            	return true;
            }
        }
        return false;
    }

    public boolean isMissing(org.dom4j.Node node) throws javax.xml.transform.TransformerException {
        return node == null ? true : false;
    }

    public boolean isEmpty(org.dom4j.Node node) throws javax.xml.transform.TransformerException {
        if (node != null) {
            return node.getText().length() == 0;
        }
        return false;
    }
}
	class Var__tXMLMap_1__Struct {	String cod;
	}
	Var__tXMLMap_1__Struct Var__tXMLMap_1 = new Var__tXMLMap_1__Struct();
// ###############################
// # Outputs initialization
insertsStruct inserts_tmp = new insertsStruct();
insertsStruct inserts_save = null;
// ###############################
		int nb_line_tXMLMap_1 = 0; 
	
    XML_API_tXMLMap_1 xml_api_tXMLMap_1 = new XML_API_tXMLMap_1();


	            
 



/**
 * [tXMLMap_1 begin ] stop
 */



	
	/**
	 * [tExtractXMLField_1 begin ] start
	 */

	

	
		
		ok_Hash.put("tExtractXMLField_1", false);
		start_Hash.put("tExtractXMLField_1", System.currentTimeMillis());
		
	
	currentComponent="tExtractXMLField_1";

	
			if (execStat) {
				if(resourceMap.get("inIterateVComp") == null){
					
						runStat.updateStatOnConnection("row1" + iterateId, 0, 0);
					
				}
			} 

		
		int tos_count_tExtractXMLField_1 = 0;
		
    	class BytesLimit65535_tExtractXMLField_1{
    		public void limitLog4jByte() throws Exception{
    			
    		}
    	}
    	
        new BytesLimit65535_tExtractXMLField_1().limitLog4jByte();

int nb_line_tExtractXMLField_1 = 0;

class NameSpaceTool_tExtractXMLField_1 {

    public java.util.HashMap<String, String> xmlNameSpaceMap = new java.util.HashMap<String, String>();
    
	private java.util.List<String> defualtNSPath = new java.util.ArrayList<String>();

    public void countNSMap(org.dom4j.Element el) {
        for (org.dom4j.Namespace ns : (java.util.List<org.dom4j.Namespace>) el.declaredNamespaces()) {
            if (ns.getPrefix().trim().length() == 0) {
                xmlNameSpaceMap.put("pre"+defualtNSPath.size(), ns.getURI());
                String path = "";
                org.dom4j.Element elTmp = el;
                while (elTmp != null) {
                   	if (elTmp.getNamespacePrefix() != null && elTmp.getNamespacePrefix().length() > 0) {
                        path = "/" + elTmp.getNamespacePrefix() + ":" + elTmp.getName() + path;
                    } else {
                        path = "/" + elTmp.getName() + path;
                    }
                    elTmp = elTmp.getParent();
                }
                defualtNSPath.add(path);
            } else {
                xmlNameSpaceMap.put(ns.getPrefix(), ns.getURI());
            }

        }
        for (org.dom4j.Element e : (java.util.List<org.dom4j.Element>) el.elements()) {
            countNSMap(e);
        }
    }
    
    /**
	 *	the regex for the xpath like that : 
	 *	case 1 : functionA(locationXPathExpression) 
	 *	case 2 : fn:functionA(locationXPathExpression) 
	 *	case 3 : functionA(functionB(locationXPathExpression))
	 *	case 4 : fn:functionA(fn:functionB(locationXPathExpression))
	 *	and like that.
	*/
	private java.util.regex.Pattern simpleFunctionPattern;
	private StringBuffer stringBuffer;
	private java.util.Map<String,String> resultCache;
	
	public String addDefaultNSPrefix(final String xpathExpression, String loopPath) {
	    if (defualtNSPath.size() < 1) {
        	return xpathExpression;
    	}
    	
    	if(resultCache == null) {
    		resultCache = new java.util.HashMap<String,String>();
    	}
    	
    	String resultXpathExpression = resultCache.get(xpathExpression);
		if(resultXpathExpression!=null) {
    		return resultXpathExpression;
    	}
    	
    	String locationPathExpression = xpathExpression;
    	
    	if(simpleFunctionPattern == null) {
    		simpleFunctionPattern = java.util.regex.Pattern.compile("([a-zA-z0-9]+:)?[a-zA-Z]+-?[A-Za-z]+\\(.*\\)");
    	}
    	
    	boolean isSimpleFunctionXPath = simpleFunctionPattern.matcher(xpathExpression).matches();
    	String tail = null;
    	if(isSimpleFunctionXPath) {
			int start = xpathExpression.lastIndexOf('(');
			int end = xpathExpression.indexOf(')');
			if(start < end) {
			    if(stringBuffer == null) {
    				stringBuffer = new StringBuffer();
    			}
				locationPathExpression = xpathExpression.substring(start+1,end);
				stringBuffer.append(xpathExpression.substring(0,start+1));
				tail = xpathExpression.substring(end);
			} else {
				isSimpleFunctionXPath = false;
			}
    	}
    	
    	locationPathExpression = addDefaultNSPrefixForLocationXPathExpression(locationPathExpression,loopPath);
    	
    	resultXpathExpression = locationPathExpression;
    	
    	if(isSimpleFunctionXPath) {
        	stringBuffer.append(locationPathExpression);
    		stringBuffer.append(tail);
    		resultXpathExpression = stringBuffer.toString();
    		stringBuffer.setLength(0);
        }
    	
    	resultCache.put(xpathExpression,resultXpathExpression);
    	return resultXpathExpression;
	}
	
    private String addDefaultNSPrefixForLocationXPathExpression(String path, String loopPath) {
    	String fullPath = loopPath;
    	if(!path.equals(fullPath)){
        	for (String tmp : path.split("/")) {
        		if (("..").equals(tmp)) {
                    fullPath = fullPath.substring(0, fullPath.lastIndexOf("/"));
                } else {
                    fullPath += "/" + tmp;
                }
        	}
        }
    	int[] indexs = new int[fullPath.split("/").length - 1];
        java.util.Arrays.fill(indexs, -1);
        int length = 0;
        for (int i = 0; i < defualtNSPath.size(); i++) {
            if (defualtNSPath.get(i).length() > length && fullPath.startsWith(defualtNSPath.get(i))) {
                java.util.Arrays.fill(indexs, defualtNSPath.get(i).split("/").length - 2, indexs.length, i);
                length = defualtNSPath.get(i).length();
            }
        }
    
        StringBuilder newPath = new StringBuilder();
        String[] pathStrs = path.split("/");
        for (int i = 0; i < pathStrs.length; i++) {
            String tmp = pathStrs[i];
            if (newPath.length() > 0) {
                newPath.append("/");
            }
            if (tmp.length() > 0 && tmp.indexOf(":") == -1 && tmp.indexOf(".") == -1 /*&& tmp.indexOf("@") == -1*/) {
                int index = indexs[i + indexs.length - pathStrs.length];
                if (index >= 0) {
                	//==== add by wliu to support both filter and functions==
    				if(tmp.indexOf("[")>0 && tmp.indexOf("]")>tmp.indexOf("[")){//include filter
    					String tmpStr=replaceElementWithNS(tmp,"pre"+index+":");
    					newPath.append(tmpStr);
    				}else{
    					if(tmp.indexOf("@") != -1 || tmp.indexOf("(")<tmp.indexOf(")")){  // include attribute
    						newPath.append(tmp);
    					}else{
    				//==add end=======	
                    		newPath.append("pre").append(index).append(":").append(tmp);
                    	}
                    }                    
                } else {
                    newPath.append(tmp);
                }
            } else {
                newPath.append(tmp);
            }
        }
        return newPath.toString();
    }
    
	private String matches = "@*\\b[a-z|A-Z|_]+[[-]*\\w]*\\b[^'|^\\(]";
    private java.util.regex.Pattern pattern = java.util.regex.Pattern.compile(matches);
    
	private String replaceElementWithNS(String global, String pre){

        java.util.regex.Matcher match = pattern.matcher(global);
        StringBuffer sb = new StringBuffer();
        match.reset();
        while (match.find()) {
            String group = match.group();
            String tmp = "";
            if (group.toLowerCase().matches("\\b(div|mod|and|or)\\b.*") || group.matches("@.*")) {
                tmp = group;
            } else {
                tmp = tmp + pre + group;
            }
            match.appendReplacement(sb, tmp);
        }
        match.appendTail(sb);
        
        return sb.toString();
	}
	
}

class XML_API_tExtractXMLField_1{
	public boolean isDefNull(org.dom4j.Node node) throws javax.xml.transform.TransformerException {
        if (node != null && node instanceof org.dom4j.Element) {
        	org.dom4j.Attribute attri = ((org.dom4j.Element)node).attribute("nil");
        	if(attri != null && ("true").equals(attri.getText())){
            	return true;
            }
        }
        return false;
    }

    public boolean isMissing(org.dom4j.Node node) throws javax.xml.transform.TransformerException {
        return node == null ? true : false;
    }

    public boolean isEmpty(org.dom4j.Node node) throws javax.xml.transform.TransformerException {
        if (node != null) {
            return node.getText().length() == 0;
        }
        return false;
    }
}

XML_API_tExtractXMLField_1 xml_api_tExtractXMLField_1 = new XML_API_tExtractXMLField_1();
 



/**
 * [tExtractXMLField_1 begin ] stop
 */



	
	/**
	 * [tRESTClient_2 begin ] start
	 */

	

	
		
		ok_Hash.put("tRESTClient_2", false);
		start_Hash.put("tRESTClient_2", System.currentTimeMillis());
		
	
	currentComponent="tRESTClient_2";

	
		int tos_count_tRESTClient_2 = 0;
		
    	class BytesLimit65535_tRESTClient_2{
    		public void limitLog4jByte() throws Exception{
    			
    		}
    	}
    	
        new BytesLimit65535_tRESTClient_2().limitLog4jByte();

 



/**
 * [tRESTClient_2 begin ] stop
 */
	
	/**
	 * [tRESTClient_2 main ] start
	 */

	

	
	
	currentComponent="tRESTClient_2";

	
	row1 = null;

// expected response body
Object responseDoc_tRESTClient_2 = null;

try {
	// request body
	org.dom4j.Document requestDoc_tRESTClient_2 = null;
	String requestString_tRESTClient_2 = null;

	Object requestBody_tRESTClient_2 = requestDoc_tRESTClient_2 != null ? requestDoc_tRESTClient_2 : requestString_tRESTClient_2;

	

    //resposne class name
	Class<?> responseClass_tRESTClient_2
		= org.dom4j.Document.class;

	// create web client instance
	org.apache.cxf.jaxrs.client.JAXRSClientFactoryBean factoryBean_tRESTClient_2 =
			new org.apache.cxf.jaxrs.client.JAXRSClientFactoryBean();

	boolean inOSGi = routines.system.BundleUtils.inOSGi();

	final java.util.List<org.apache.cxf.feature.Feature> features_tRESTClient_2 =
			new java.util.ArrayList<org.apache.cxf.feature.Feature>();

	
		String url = "http://apilayer.net";
		// {baseUri}tRESTClient
		factoryBean_tRESTClient_2.setServiceName(new javax.xml.namespace.QName(url, "tRESTClient"));
		factoryBean_tRESTClient_2.setAddress(url);
	

	

	

	

	factoryBean_tRESTClient_2.setFeatures(features_tRESTClient_2);


	java.util.List<Object> providers_tRESTClient_2 = new java.util.ArrayList<Object>();
	providers_tRESTClient_2.add(new org.apache.cxf.jaxrs.provider.dom4j.DOM4JProvider() {
		// workaround for https://jira.talendforge.org/browse/TESB-7276
		public org.dom4j.Document readFrom(Class<org.dom4j.Document> cls,
											java.lang.reflect.Type type,
											java.lang.annotation.Annotation[] anns,
											javax.ws.rs.core.MediaType mt,
											javax.ws.rs.core.MultivaluedMap<String, String> headers,
											java.io.InputStream is)
				throws IOException, javax.ws.rs.WebApplicationException {
			String contentLength = headers.getFirst("Content-Length");
			if (!org.apache.cxf.common.util.StringUtils.isEmpty(contentLength)
					&& Integer.valueOf(contentLength) <= 0) {
				try {
					return org.dom4j.DocumentHelper.parseText("<root/>");
				} catch (org.dom4j.DocumentException e_tRESTClient_2) {
					e_tRESTClient_2.printStackTrace();
				}
				return null;
			}
			return super.readFrom(cls, type, anns, mt, headers, is);
		}
	});
	org.apache.cxf.jaxrs.provider.json.JSONProvider jsonProvider_tRESTClient_2 =
			new org.apache.cxf.jaxrs.provider.json.JSONProvider();
		jsonProvider_tRESTClient_2.setIgnoreNamespaces(true);
		jsonProvider_tRESTClient_2.setAttributesToElements(true);
	
	
		jsonProvider_tRESTClient_2.setSupportUnwrapped(true);
		jsonProvider_tRESTClient_2.setWrapperName("root");
	
	
		jsonProvider_tRESTClient_2.setDropRootElement(false);
		jsonProvider_tRESTClient_2.setConvertTypesToStrings(false);
	providers_tRESTClient_2.add(jsonProvider_tRESTClient_2);
	factoryBean_tRESTClient_2.setProviders(providers_tRESTClient_2);
	factoryBean_tRESTClient_2.setTransportId("http://cxf.apache.org/transports/http");

	boolean use_auth_tRESTClient_2 = false;
	if (use_auth_tRESTClient_2 && "SAML".equals("BASIC")) {
		if (!inOSGi) {
			throw new IllegalArgumentException("SAML based security scenarios are not supported in Studio (standalone)");
		}
		// set SAML Token authentication
		
		 
	final String decryptedPassword_tRESTClient_2 = routines.system.PasswordEncryptUtil.decryptPassword("a54bbfcc1190b7e1f4f7aba1746784ea");

		org.apache.cxf.ws.security.trust.STSClient stsClient =
			org.talend.esb.security.saml.STSClientUtils.createSTSClient(factoryBean_tRESTClient_2.getBus(),
				"username", decryptedPassword_tRESTClient_2);
		
		org.talend.esb.security.saml.SAMLRESTUtils.configureClient(factoryBean_tRESTClient_2, stsClient);
	}

	org.apache.cxf.jaxrs.client.WebClient webClient_tRESTClient_2 = factoryBean_tRESTClient_2.createWebClient();

	// set request path
	webClient_tRESTClient_2.path("/api/live");

	// set connection properties
	org.apache.cxf.jaxrs.client.ClientConfiguration clientConfig_tRESTClient_2 = org.apache.cxf.jaxrs.client.WebClient.getConfig(webClient_tRESTClient_2);
	org.apache.cxf.transport.http.HTTPConduit conduit_tRESTClient_2 = clientConfig_tRESTClient_2.getHttpConduit();

    if (clientConfig_tRESTClient_2.getEndpoint() != null
            && clientConfig_tRESTClient_2.getEndpoint().getEndpointInfo() != null) {
        clientConfig_tRESTClient_2.getEndpoint().getEndpointInfo().setProperty("enable.webclient.operation.reporting",
                                                                          true);
    }

	

	if (use_auth_tRESTClient_2 && "BASIC".equals("BASIC")) {
		// set BASIC auth
		
		 
	final String decryptedPassword_tRESTClient_2 = routines.system.PasswordEncryptUtil.decryptPassword("a54bbfcc1190b7e1f4f7aba1746784ea");

		org.apache.cxf.configuration.security.AuthorizationPolicy authPolicy_tRESTClient_2 = new org.apache.cxf.configuration.security.AuthorizationPolicy();
			authPolicy_tRESTClient_2.setAuthorizationType("Basic");
			authPolicy_tRESTClient_2.setUserName("username");
			authPolicy_tRESTClient_2.setPassword(decryptedPassword_tRESTClient_2);
		conduit_tRESTClient_2.setAuthorization(authPolicy_tRESTClient_2);
	} else if (use_auth_tRESTClient_2 && "HTTP Digest".equals("BASIC")) {
		// set Digest auth
		
		 
	final String decryptedPassword_tRESTClient_2 = routines.system.PasswordEncryptUtil.decryptPassword("a54bbfcc1190b7e1f4f7aba1746784ea");

		org.apache.cxf.configuration.security.AuthorizationPolicy authPolicy_tRESTClient_2 = new org.apache.cxf.configuration.security.AuthorizationPolicy();
		authPolicy_tRESTClient_2.setAuthorizationType("Digest");
		authPolicy_tRESTClient_2.setUserName("username");
		authPolicy_tRESTClient_2.setPassword(decryptedPassword_tRESTClient_2);
		conduit_tRESTClient_2.setAuthorization(authPolicy_tRESTClient_2);
	}

	if (!inOSGi) {
		conduit_tRESTClient_2.getClient().setReceiveTimeout((long)(60 * 1000L));
		conduit_tRESTClient_2.getClient().setConnectionTimeout((long)(30 * 1000L));
		boolean use_proxy_tRESTClient_2 = false;
		if (use_proxy_tRESTClient_2) {
			
			 
	final String decryptedPassword_tRESTClient_2 = routines.system.PasswordEncryptUtil.decryptPassword("f4f7aba1746784ea");

			conduit_tRESTClient_2.getClient().setProxyServer("61.163.92.4");
			conduit_tRESTClient_2.getClient().setProxyServerPort(Integer.valueOf(8080));
			conduit_tRESTClient_2.getProxyAuthorization().setUserName("");
			conduit_tRESTClient_2.getProxyAuthorization().setPassword(decryptedPassword_tRESTClient_2);
		}
	}

	

	

	

	
		// set Accept-Type
		webClient_tRESTClient_2.accept("application/xml");
	

	
		// set optional query and header properties if any
	
	if (use_auth_tRESTClient_2 && "OAUTH2_BEARER".equals("BASIC")) {
		// set oAuth2 bearer token
		webClient_tRESTClient_2.header("Authorization", "Bearer " + "");
	}
	
	if (use_auth_tRESTClient_2 && "OIDC_PASSWORD_GRANT".equals("BASIC")) {
 
	final String decryptedPassword_tRESTClient_2 = routines.system.PasswordEncryptUtil.decryptPassword("a54bbfcc1190b7e1f4f7aba1746784ea");

        String username_tRESTClient_2 = "username";
        String password_tRESTClient_2 = decryptedPassword_tRESTClient_2;

        String bearerHeader_tRESTClient_2 = null;

        try {
			if (!inOSGi) {
				org.springframework.context.support.ClassPathXmlApplicationContext context_tRESTClient_2 =
					new org.springframework.context.support.ClassPathXmlApplicationContext("META-INF/tesb/oidc-context.xml");
				org.talend.esb.security.oidc.OidcConfiguration oidcConfiguration_tRESTClient_2 = context_tRESTClient_2.getBean(org.talend.esb.security.oidc.OidcConfiguration.class);
				bearerHeader_tRESTClient_2 = org.talend.esb.security.oidc.OidcClientUtils.oidcClientBearer(username_tRESTClient_2, password_tRESTClient_2, oidcConfiguration_tRESTClient_2);
			}else{
				bearerHeader_tRESTClient_2 = org.talend.esb.security.oidc.OidcClientUtils.oidcClientBearer(username_tRESTClient_2, password_tRESTClient_2);
			}
		} catch (Exception ex) {
            throw new javax.ws.rs.WebApplicationException("Failed to get OIDC access token: ", ex);
        }

		webClient_tRESTClient_2.header("Authorization", bearerHeader_tRESTClient_2);
	}
    
	// if FORM request then capture query parameters into Form, otherwise set them as queries
	
		
			webClient_tRESTClient_2.query("access_key" ,"dae854cf61ae211b629e41056eaa4f63");
		
			webClient_tRESTClient_2.query("currencies" ,"EUR,GBP,COP,JPY");
		
			webClient_tRESTClient_2.query("source" ,"USD");
		
			webClient_tRESTClient_2.query("format" ,"1");
		
	


	try {
		// start send request
		
			responseDoc_tRESTClient_2 = webClient_tRESTClient_2.get(responseClass_tRESTClient_2);
		


		int webClientResponseStatus_tRESTClient_2 = webClient_tRESTClient_2.getResponse().getStatus();
		if (webClientResponseStatus_tRESTClient_2 >= 300) {
			throw new javax.ws.rs.WebApplicationException(webClient_tRESTClient_2.getResponse());
		}

		
			if (row1 == null) {
				row1 = new row1Struct();
			}

			row1.statusCode = webClientResponseStatus_tRESTClient_2;
			
				
				{
					Object responseObj_tRESTClient_2 = responseDoc_tRESTClient_2;
				
				if(responseObj_tRESTClient_2 != null){
					if (responseClass_tRESTClient_2 == String.class) {
						row1.string = (String) responseObj_tRESTClient_2;
					} else {
						routines.system.Document responseTalendDoc_tRESTClient_2 = null;
						if (null != responseObj_tRESTClient_2) {
							responseTalendDoc_tRESTClient_2 = new routines.system.Document();
							responseTalendDoc_tRESTClient_2.setDocument((org.dom4j.Document) responseObj_tRESTClient_2);
						}
						row1.body = responseTalendDoc_tRESTClient_2;
					}
				}
			}
			


			globalMap.put("tRESTClient_2_HEADERS", webClient_tRESTClient_2.getResponse().getHeaders());
			
			
			
		

	} catch (javax.ws.rs.WebApplicationException ex_tRESTClient_2) {
		
			throw ex_tRESTClient_2;
		
	}

} catch(Exception e_tRESTClient_2) {
	
		throw new TalendException(e_tRESTClient_2, currentComponent, globalMap);
	
}


 


	tos_count_tRESTClient_2++;

/**
 * [tRESTClient_2 main ] stop
 */
	
	/**
	 * [tRESTClient_2 process_data_begin ] start
	 */

	

	
	
	currentComponent="tRESTClient_2";

	

 



/**
 * [tRESTClient_2 process_data_begin ] stop
 */
// Start of branch "row1"
if(row1 != null) { 



	
	/**
	 * [tExtractXMLField_1 main ] start
	 */

	

	
	
	currentComponent="tExtractXMLField_1";

	

			//row1
			//row1


			
				if(execStat){
					runStat.updateStatOnConnection("row1"+iterateId,1, 1);
				} 
			

		

	String xmlStr_tExtractXMLField_1 = null;
	routines.system.Document xmlDocument_tExtractXMLField_1 = null;
	if(row1.body!=null){
				xmlDocument_tExtractXMLField_1 = row1.body;
	}
			if(xmlDocument_tExtractXMLField_1!=null && xmlDocument_tExtractXMLField_1.getDocument()!=null){// C_01
row2 = null;
	NameSpaceTool_tExtractXMLField_1 nsTool_tExtractXMLField_1 = new NameSpaceTool_tExtractXMLField_1();
    org.dom4j.io.SAXReader reader_tExtractXMLField_1 = new org.dom4j.io.SAXReader();
	
    org.dom4j.Document doc_tExtractXMLField_1 = null;
    java.util.HashMap xmlNameSpaceMap_tExtractXMLField_1 = null;
    org.dom4j.XPath x_tExtractXMLField_1 = null;
    java.util.List<org.dom4j.tree.AbstractNode> nodeList_tExtractXMLField_1 = null;
		String loopQuery_tExtractXMLField_1 = "/root/quotes/*"; 
	
    boolean isStructError_tExtractXMLField_1= true;
        
    try{
		
	    	doc_tExtractXMLField_1= xmlDocument_tExtractXMLField_1.getDocument();
	    
	    nsTool_tExtractXMLField_1.countNSMap(doc_tExtractXMLField_1.getRootElement());
	    xmlNameSpaceMap_tExtractXMLField_1 = nsTool_tExtractXMLField_1.xmlNameSpaceMap;

    	x_tExtractXMLField_1 = doc_tExtractXMLField_1.createXPath(nsTool_tExtractXMLField_1.addDefaultNSPrefix(loopQuery_tExtractXMLField_1,loopQuery_tExtractXMLField_1));
      
    	x_tExtractXMLField_1.setNamespaceURIs(xmlNameSpaceMap_tExtractXMLField_1); 
    
		 
    	nodeList_tExtractXMLField_1 = (java.util.List<org.dom4j.tree.AbstractNode>)x_tExtractXMLField_1.selectNodes(doc_tExtractXMLField_1);
    	
    	isStructError_tExtractXMLField_1 = false;
    	
    }catch(java.lang.Exception ex_tExtractXMLField_1){
    System.err.println(ex_tExtractXMLField_1.getMessage());
    }
    
    org.dom4j.Node node_tExtractXMLField_1 = null;
    String str_tExtractXMLField_1 = "";
    boolean resultIsNode_tExtractXMLField_1 = true;
    for(int i_tExtractXMLField_1=0; isStructError_tExtractXMLField_1 || (nodeList_tExtractXMLField_1!=null && i_tExtractXMLField_1 < nodeList_tExtractXMLField_1.size());i_tExtractXMLField_1++){
    	
    	if(!isStructError_tExtractXMLField_1){
			row2 = null;
    		row2 = new row2Struct();
    	
    		org.dom4j.tree.AbstractNode temp_tExtractXMLField_1 = nodeList_tExtractXMLField_1.get(i_tExtractXMLField_1);
	
	    	nb_line_tExtractXMLField_1++;	
			try{
				org.dom4j.XPath xTmp0_tExtractXMLField_1 = temp_tExtractXMLField_1.createXPath(nsTool_tExtractXMLField_1.addDefaultNSPrefix("name()",loopQuery_tExtractXMLField_1));
			    xTmp0_tExtractXMLField_1.setNamespaceURIs(xmlNameSpaceMap_tExtractXMLField_1);
				
			    Object obj0_tExtractXMLField_1 = xTmp0_tExtractXMLField_1.evaluate(temp_tExtractXMLField_1);
			    if(obj0_tExtractXMLField_1 instanceof String || obj0_tExtractXMLField_1 instanceof Number){
			    	resultIsNode_tExtractXMLField_1 = false;
    				str_tExtractXMLField_1 = String.valueOf(obj0_tExtractXMLField_1);
   				}else{
   					resultIsNode_tExtractXMLField_1 = true;
				    node_tExtractXMLField_1 = xTmp0_tExtractXMLField_1.selectSingleNode(temp_tExtractXMLField_1);
				    str_tExtractXMLField_1 = xTmp0_tExtractXMLField_1.valueOf(temp_tExtractXMLField_1);
				}
									if(resultIsNode_tExtractXMLField_1 && xml_api_tExtractXMLField_1.isDefNull(node_tExtractXMLField_1)){
											row2.name =null;
									}else if(resultIsNode_tExtractXMLField_1 && xml_api_tExtractXMLField_1.isEmpty(node_tExtractXMLField_1)){
										row2.name ="";
									}else if(resultIsNode_tExtractXMLField_1 && xml_api_tExtractXMLField_1.isMissing(node_tExtractXMLField_1 )){ 
										row2.name =null;
									}else{
				row2.name = str_tExtractXMLField_1;
									}
				org.dom4j.XPath xTmp1_tExtractXMLField_1 = temp_tExtractXMLField_1.createXPath(nsTool_tExtractXMLField_1.addDefaultNSPrefix("number()",loopQuery_tExtractXMLField_1));
			    xTmp1_tExtractXMLField_1.setNamespaceURIs(xmlNameSpaceMap_tExtractXMLField_1);
				
			    Object obj1_tExtractXMLField_1 = xTmp1_tExtractXMLField_1.evaluate(temp_tExtractXMLField_1);
			    if(obj1_tExtractXMLField_1 instanceof String || obj1_tExtractXMLField_1 instanceof Number){
			    	resultIsNode_tExtractXMLField_1 = false;
    				str_tExtractXMLField_1 = String.valueOf(obj1_tExtractXMLField_1);
   				}else{
   					resultIsNode_tExtractXMLField_1 = true;
				    node_tExtractXMLField_1 = xTmp1_tExtractXMLField_1.selectSingleNode(temp_tExtractXMLField_1);
				    str_tExtractXMLField_1 = xTmp1_tExtractXMLField_1.valueOf(temp_tExtractXMLField_1);
				}	
										if(resultIsNode_tExtractXMLField_1 && xml_api_tExtractXMLField_1.isDefNull(node_tExtractXMLField_1)){
											row2.exchange =null;
										}else if(resultIsNode_tExtractXMLField_1 && (xml_api_tExtractXMLField_1.isEmpty(node_tExtractXMLField_1) || xml_api_tExtractXMLField_1.isMissing(node_tExtractXMLField_1))){
											row2.exchange=null;
										}else{
				row2.exchange = ParserUtils.parseTo_Double(str_tExtractXMLField_1);
									}
				org.dom4j.XPath xTmp2_tExtractXMLField_1 = temp_tExtractXMLField_1.createXPath(nsTool_tExtractXMLField_1.addDefaultNSPrefix("../../timestamp",loopQuery_tExtractXMLField_1));
			    xTmp2_tExtractXMLField_1.setNamespaceURIs(xmlNameSpaceMap_tExtractXMLField_1);
				
			    Object obj2_tExtractXMLField_1 = xTmp2_tExtractXMLField_1.evaluate(temp_tExtractXMLField_1);
			    if(obj2_tExtractXMLField_1 instanceof String || obj2_tExtractXMLField_1 instanceof Number){
			    	resultIsNode_tExtractXMLField_1 = false;
    				str_tExtractXMLField_1 = String.valueOf(obj2_tExtractXMLField_1);
   				}else{
   					resultIsNode_tExtractXMLField_1 = true;
				    node_tExtractXMLField_1 = xTmp2_tExtractXMLField_1.selectSingleNode(temp_tExtractXMLField_1);
				    str_tExtractXMLField_1 = xTmp2_tExtractXMLField_1.valueOf(temp_tExtractXMLField_1);
				}	
										if(resultIsNode_tExtractXMLField_1 && xml_api_tExtractXMLField_1.isDefNull(node_tExtractXMLField_1)){
											row2.date =null;
										}else if(resultIsNode_tExtractXMLField_1 && (xml_api_tExtractXMLField_1.isEmpty(node_tExtractXMLField_1) || xml_api_tExtractXMLField_1.isMissing(node_tExtractXMLField_1))){
											row2.date=null;
										}else{
				row2.date = ParserUtils.parseTo_Long(str_tExtractXMLField_1);
									}
}catch(java.lang.Exception ex_tExtractXMLField_1){
    System.err.println(ex_tExtractXMLField_1.getMessage());
    row2 = null;
    	}
    }
    
    isStructError_tExtractXMLField_1 = false;


   globalMap.put("tExtractXMLField_1_NB_LINE", nb_line_tExtractXMLField_1);

 


	tos_count_tExtractXMLField_1++;

/**
 * [tExtractXMLField_1 main ] stop
 */
	
	/**
	 * [tExtractXMLField_1 process_data_begin ] start
	 */

	

	
	
	currentComponent="tExtractXMLField_1";

	

 



/**
 * [tExtractXMLField_1 process_data_begin ] stop
 */
// Start of branch "row2"
if(row2 != null) { 



	
	/**
	 * [tXMLMap_1 main ] start
	 */

	

	
	
	currentComponent="tXMLMap_1";

	

			//row2
			//row2


			
				if(execStat){
					runStat.updateStatOnConnection("row2"+iterateId,1, 1);
				} 
			

		


	boolean rejectedInnerJoin_tXMLMap_1 = false;
	boolean rejectedDocInnerJoin_tXMLMap_1 = false;
	boolean mainRowRejected_tXMLMap_1 = false;
	boolean isMatchDocRowtXMLMap_1 = false;
	  
	
		


			
        { // start of Var scope
        
	        // ###############################
        	// # Vars tables
        
Var__tXMLMap_1__Struct Var = Var__tXMLMap_1;
					
Var.cod =  row2.name;
		// ###############################
		// # Output tables

inserts = null;


// # Output table : 'inserts'
inserts_tmp.name = row2.name;
inserts_tmp.exchange = row2.exchange;
inserts_tmp.date = TalendDate.formatDate("dd/MM/yyyy",routineFecha.millisTOdate(row2.date) ) ;
inserts_tmp.currency1 = "USD";
inserts_tmp.currency2 = StringHandling.EREPLACE(row2.name,"USD","") ;
inserts = inserts_tmp;
// ###############################

} // end of Var scope

rejectedInnerJoin_tXMLMap_1 = false;



 


	tos_count_tXMLMap_1++;

/**
 * [tXMLMap_1 main ] stop
 */
	
	/**
	 * [tXMLMap_1 process_data_begin ] start
	 */

	

	
	
	currentComponent="tXMLMap_1";

	

 



/**
 * [tXMLMap_1 process_data_begin ] stop
 */
// Start of branch "inserts"
if(inserts != null) { 



	
	/**
	 * [tMysqlOutput_2 main ] start
	 */

	

	
	
	currentComponent="tMysqlOutput_2";

	

			//inserts
			//inserts


			
				if(execStat){
					runStat.updateStatOnConnection("inserts"+iterateId,1, 1);
				} 
			

		



        whetherReject_tMysqlOutput_2 = false;
                            if(inserts.name == null) {
pstmt_tMysqlOutput_2.setNull(1, java.sql.Types.VARCHAR);
} else {pstmt_tMysqlOutput_2.setString(1, inserts.name);
}

                            if(inserts.exchange == null) {
pstmt_tMysqlOutput_2.setNull(2, java.sql.Types.DOUBLE);
} else {pstmt_tMysqlOutput_2.setDouble(2, inserts.exchange);
}

                            if(inserts.date == null) {
pstmt_tMysqlOutput_2.setNull(3, java.sql.Types.VARCHAR);
} else {pstmt_tMysqlOutput_2.setString(3, inserts.date);
}

                            if(inserts.currency1 == null) {
pstmt_tMysqlOutput_2.setNull(4, java.sql.Types.VARCHAR);
} else {pstmt_tMysqlOutput_2.setString(4, inserts.currency1);
}

                            if(inserts.currency2 == null) {
pstmt_tMysqlOutput_2.setNull(5, java.sql.Types.VARCHAR);
} else {pstmt_tMysqlOutput_2.setString(5, inserts.currency2);
}

                    pstmt_tMysqlOutput_2.addBatch();
                    nb_line_tMysqlOutput_2++;

                      batchSizeCounter_tMysqlOutput_2++;
                if ( batchSize_tMysqlOutput_2 <= batchSizeCounter_tMysqlOutput_2) {
                try {
                        int countSum_tMysqlOutput_2 = 0;
                        for(int countEach_tMysqlOutput_2: pstmt_tMysqlOutput_2.executeBatch()) {
                            countSum_tMysqlOutput_2 += (countEach_tMysqlOutput_2 < 0 ? 0 : 1);
                        }
                        insertedCount_tMysqlOutput_2 += countSum_tMysqlOutput_2;
                }catch (java.sql.BatchUpdateException e){
                    int countSum_tMysqlOutput_2 = 0;
                    for(int countEach_tMysqlOutput_2: e.getUpdateCounts()) {
                        countSum_tMysqlOutput_2 += (countEach_tMysqlOutput_2 < 0 ? 0 : countEach_tMysqlOutput_2);
                    }
                    insertedCount_tMysqlOutput_2 += countSum_tMysqlOutput_2;
                    System.err.println(e.getMessage());
                }

                batchSizeCounter_tMysqlOutput_2 = 0;
            }
                commitCounter_tMysqlOutput_2++;

                if(commitEvery_tMysqlOutput_2 <= commitCounter_tMysqlOutput_2) {

                try {
                        int countSum_tMysqlOutput_2 = 0;
                        for(int countEach_tMysqlOutput_2: pstmt_tMysqlOutput_2.executeBatch()) {
                            countSum_tMysqlOutput_2 += (countEach_tMysqlOutput_2 < 0 ? 0 : 1);
                        }
                        insertedCount_tMysqlOutput_2 += countSum_tMysqlOutput_2;
                }catch (java.sql.BatchUpdateException e){
                    int countSum_tMysqlOutput_2 = 0;
                    for(int countEach_tMysqlOutput_2: e.getUpdateCounts()) {
                        countSum_tMysqlOutput_2 += (countEach_tMysqlOutput_2 < 0 ? 0 : countEach_tMysqlOutput_2);
                    }
                    insertedCount_tMysqlOutput_2 += countSum_tMysqlOutput_2;
                    System.err.println(e.getMessage());

                }
                    conn_tMysqlOutput_2.commit();
                    commitCounter_tMysqlOutput_2=0;

                }


 


	tos_count_tMysqlOutput_2++;

/**
 * [tMysqlOutput_2 main ] stop
 */
	
	/**
	 * [tMysqlOutput_2 process_data_begin ] start
	 */

	

	
	
	currentComponent="tMysqlOutput_2";

	

 



/**
 * [tMysqlOutput_2 process_data_begin ] stop
 */
	
	/**
	 * [tMysqlOutput_2 process_data_end ] start
	 */

	

	
	
	currentComponent="tMysqlOutput_2";

	

 



/**
 * [tMysqlOutput_2 process_data_end ] stop
 */

} // End of branch "inserts"




	
	/**
	 * [tXMLMap_1 process_data_end ] start
	 */

	

	
	
	currentComponent="tXMLMap_1";

	

 



/**
 * [tXMLMap_1 process_data_end ] stop
 */

} // End of branch "row2"

		// end for
	}


	
		} // C_01
	
	
	/**
	 * [tExtractXMLField_1 process_data_end ] start
	 */

	

	
	
	currentComponent="tExtractXMLField_1";

	

 



/**
 * [tExtractXMLField_1 process_data_end ] stop
 */

} // End of branch "row1"




	
	/**
	 * [tRESTClient_2 process_data_end ] start
	 */

	

	
	
	currentComponent="tRESTClient_2";

	

 



/**
 * [tRESTClient_2 process_data_end ] stop
 */
	
	/**
	 * [tRESTClient_2 end ] start
	 */

	

	
	
	currentComponent="tRESTClient_2";

	


// [tRESTCliend_end]
 

ok_Hash.put("tRESTClient_2", true);
end_Hash.put("tRESTClient_2", System.currentTimeMillis());




/**
 * [tRESTClient_2 end ] stop
 */

	
	/**
	 * [tExtractXMLField_1 end ] start
	 */

	

	
	
	currentComponent="tExtractXMLField_1";

	



globalMap.put("tExtractXMLField_1_NB_LINE", nb_line_tExtractXMLField_1);

			if(execStat){
				if(resourceMap.get("inIterateVComp") == null || !((Boolean)resourceMap.get("inIterateVComp"))){
			 		runStat.updateStatOnConnection("row1"+iterateId,2, 0); 
			 	}
			}
		
 

ok_Hash.put("tExtractXMLField_1", true);
end_Hash.put("tExtractXMLField_1", System.currentTimeMillis());




/**
 * [tExtractXMLField_1 end ] stop
 */

	
	/**
	 * [tXMLMap_1 end ] start
	 */

	

	
	
	currentComponent="tXMLMap_1";

	

			if(execStat){
				if(resourceMap.get("inIterateVComp") == null || !((Boolean)resourceMap.get("inIterateVComp"))){
			 		runStat.updateStatOnConnection("row2"+iterateId,2, 0); 
			 	}
			}
		
 

ok_Hash.put("tXMLMap_1", true);
end_Hash.put("tXMLMap_1", System.currentTimeMillis());




/**
 * [tXMLMap_1 end ] stop
 */

	
	/**
	 * [tMysqlOutput_2 end ] start
	 */

	

	
	
	currentComponent="tMysqlOutput_2";

	



                try {
                		if (batchSizeCounter_tMysqlOutput_2 != 0) {
							int countSum_tMysqlOutput_2 = 0;
							
							for(int countEach_tMysqlOutput_2: pstmt_tMysqlOutput_2.executeBatch()) {
								countSum_tMysqlOutput_2 += (countEach_tMysqlOutput_2 < 0 ? 0 : 1);
							}
							
	            	    	
	            	    		insertedCount_tMysqlOutput_2 += countSum_tMysqlOutput_2;
	            	    	
            	    	}

                }catch (java.sql.BatchUpdateException e){
                	
                	int countSum_tMysqlOutput_2 = 0;
					for(int countEach_tMysqlOutput_2: e.getUpdateCounts()) {
						countSum_tMysqlOutput_2 += (countEach_tMysqlOutput_2 < 0 ? 0 : countEach_tMysqlOutput_2);
					}
					
            	    insertedCount_tMysqlOutput_2 += countSum_tMysqlOutput_2;
	    	    	
					globalMap.put(currentComponent+"_ERROR_MESSAGE",e.getMessage());
                	System.err.println(e.getMessage());
                	
                }
                batchSizeCounter_tMysqlOutput_2 = 0;
    		
	

        if(pstmt_tMysqlOutput_2 != null) {
			
				pstmt_tMysqlOutput_2.close();
			
        }

    	if (commitCounter_tMysqlOutput_2 > 0) {
    		
    		conn_tMysqlOutput_2.commit();
    		
    	}
    		
		
    	conn_tMysqlOutput_2 .close();
    	
    	resourceMap.put("finish_tMysqlOutput_2", true);
    	

	nb_line_deleted_tMysqlOutput_2=nb_line_deleted_tMysqlOutput_2+ deletedCount_tMysqlOutput_2;
	nb_line_update_tMysqlOutput_2=nb_line_update_tMysqlOutput_2 + updatedCount_tMysqlOutput_2;
	nb_line_inserted_tMysqlOutput_2=nb_line_inserted_tMysqlOutput_2 + insertedCount_tMysqlOutput_2;
	nb_line_rejected_tMysqlOutput_2=nb_line_rejected_tMysqlOutput_2 + rejectedCount_tMysqlOutput_2;
	
        globalMap.put("tMysqlOutput_2_NB_LINE",nb_line_tMysqlOutput_2);
        globalMap.put("tMysqlOutput_2_NB_LINE_UPDATED",nb_line_update_tMysqlOutput_2);
        globalMap.put("tMysqlOutput_2_NB_LINE_INSERTED",nb_line_inserted_tMysqlOutput_2);
        globalMap.put("tMysqlOutput_2_NB_LINE_DELETED",nb_line_deleted_tMysqlOutput_2);
        globalMap.put("tMysqlOutput_2_NB_LINE_REJECTED", nb_line_rejected_tMysqlOutput_2);
    
	

			if(execStat){
				if(resourceMap.get("inIterateVComp") == null || !((Boolean)resourceMap.get("inIterateVComp"))){
			 		runStat.updateStatOnConnection("inserts"+iterateId,2, 0); 
			 	}
			}
		
 

ok_Hash.put("tMysqlOutput_2", true);
end_Hash.put("tMysqlOutput_2", System.currentTimeMillis());




/**
 * [tMysqlOutput_2 end ] stop
 */









				}//end the resume

				



	
			}catch(java.lang.Exception e){	
				
				TalendException te = new TalendException(e, currentComponent, globalMap);
				
				throw te;
			}catch(java.lang.Error error){	
				
					runStat.stopThreadStat();
				
				throw error;
			}finally{
				
				try{
					
	
	/**
	 * [tRESTClient_2 finally ] start
	 */

	

	
	
	currentComponent="tRESTClient_2";

	

 



/**
 * [tRESTClient_2 finally ] stop
 */

	
	/**
	 * [tExtractXMLField_1 finally ] start
	 */

	

	
	
	currentComponent="tExtractXMLField_1";

	

 



/**
 * [tExtractXMLField_1 finally ] stop
 */

	
	/**
	 * [tXMLMap_1 finally ] start
	 */

	

	
	
	currentComponent="tXMLMap_1";

	

 



/**
 * [tXMLMap_1 finally ] stop
 */

	
	/**
	 * [tMysqlOutput_2 finally ] start
	 */

	

	
	
	currentComponent="tMysqlOutput_2";

	



	
		if(resourceMap.get("finish_tMysqlOutput_2")==null){
			if(resourceMap.get("conn_tMysqlOutput_2")!=null){
				try {
					
					
					java.sql.Connection ctn_tMysqlOutput_2 = (java.sql.Connection)resourceMap.get("conn_tMysqlOutput_2");
					
					
            		
					ctn_tMysqlOutput_2.close();
					
				} catch (java.sql.SQLException sqlEx_tMysqlOutput_2) {
					String errorMessage_tMysqlOutput_2 = "failed to close the connection in tMysqlOutput_2 :" + sqlEx_tMysqlOutput_2.getMessage();
					
					System.err.println(errorMessage_tMysqlOutput_2);
				}
			}
		}
	

 



/**
 * [tMysqlOutput_2 finally ] stop
 */









				}catch(java.lang.Exception e){	
					//ignore
				}catch(java.lang.Error error){
					//ignore
				}
				resourceMap = null;
			}
		

		globalMap.put("tRESTClient_2_SUBPROCESS_STATE", 1);
	}
	
    public String resuming_logs_dir_path = null;
    public String resuming_checkpoint_path = null;
    public String parent_part_launcher = null;
    private String resumeEntryMethodName = null;
    private boolean globalResumeTicket = false;

    public boolean watch = false;
    // portStats is null, it means don't execute the statistics
    public Integer portStats = null;
    public int portTraces = 4334;
    public String clientHost;
    public String defaultClientHost = "localhost";
    public String contextStr = "Default";
    public boolean isDefaultContext = true;
    public String pid = "0";
    public String rootPid = null;
    public String fatherPid = null;
    public String fatherNode = null;
    public long startTime = 0;
    public boolean isChildJob = false;
    public String log4jLevel = "";

    private boolean execStat = true;

    private ThreadLocal<java.util.Map<String, String>> threadLocal = new ThreadLocal<java.util.Map<String, String>>() {
        protected java.util.Map<String, String> initialValue() {
            java.util.Map<String,String> threadRunResultMap = new java.util.HashMap<String, String>();
            threadRunResultMap.put("errorCode", null);
            threadRunResultMap.put("status", "");
            return threadRunResultMap;
        };
    };


    private PropertiesWithType context_param = new PropertiesWithType();
    public java.util.Map<String, Object> parentContextMap = new java.util.HashMap<String, Object>();

    public String status= "";
    

    public static void main(String[] args){
        final xchange_api_consume xchange_api_consumeClass = new xchange_api_consume();

        int exitCode = xchange_api_consumeClass.runJobInTOS(args);

        System.exit(exitCode);
    }


    public String[][] runJob(String[] args) {

        int exitCode = runJobInTOS(args);
        String[][] bufferValue = new String[][] { { Integer.toString(exitCode) } };

        return bufferValue;
    }

    public boolean hastBufferOutputComponent() {
		boolean hastBufferOutput = false;
    	
        return hastBufferOutput;
    }

    public int runJobInTOS(String[] args) {
	   	// reset status
	   	status = "";

        String lastStr = "";
        for (String arg : args) {
            if (arg.equalsIgnoreCase("--context_param")) {
                lastStr = arg;
            } else if (lastStr.equals("")) {
                evalParam(arg);
            } else {
                evalParam(lastStr + " " + arg);
                lastStr = "";
            }
        }


        if(clientHost == null) {
            clientHost = defaultClientHost;
        }

        if(pid == null || "0".equals(pid)) {
            pid = TalendString.getAsciiRandomString(6);
        }

        if (rootPid==null) {
            rootPid = pid;
        }
        if (fatherPid==null) {
            fatherPid = pid;
        }else{
            isChildJob = true;
        }

        if (portStats != null) {
            // portStats = -1; //for testing
            if (portStats < 0 || portStats > 65535) {
                // issue:10869, the portStats is invalid, so this client socket can't open
                System.err.println("The statistics socket port " + portStats + " is invalid.");
                execStat = false;
            }
        } else {
            execStat = false;
        }

        try {
            //call job/subjob with an existing context, like: --context=production. if without this parameter, there will use the default context instead.
            java.io.InputStream inContext = xchange_api_consume.class.getClassLoader().getResourceAsStream("completo/xchange_api_consume_0_1/contexts/" + contextStr + ".properties");
            if (inContext == null) {
                inContext = xchange_api_consume.class.getClassLoader().getResourceAsStream("config/contexts/" + contextStr + ".properties");
            }
            if (inContext != null) {
                //defaultProps is in order to keep the original context value
                defaultProps.load(inContext);
                inContext.close();
                context = new ContextProperties(defaultProps);
            } else if (!isDefaultContext) {
                //print info and job continue to run, for case: context_param is not empty.
                System.err.println("Could not find the context " + contextStr);
            }

            if(!context_param.isEmpty()) {
                context.putAll(context_param);
				//set types for params from parentJobs
				for (Object key: context_param.keySet()){
					String context_key = key.toString();
					String context_type = context_param.getContextType(context_key);
					context.setContextType(context_key, context_type);

				}
            }
        } catch (java.io.IOException ie) {
            System.err.println("Could not load context "+contextStr);
            ie.printStackTrace();
        }


        // get context value from parent directly
        if (parentContextMap != null && !parentContextMap.isEmpty()) {
        }

        //Resume: init the resumeUtil
        resumeEntryMethodName = ResumeUtil.getResumeEntryMethodName(resuming_checkpoint_path);
        resumeUtil = new ResumeUtil(resuming_logs_dir_path, isChildJob, rootPid);
        resumeUtil.initCommonInfo(pid, rootPid, fatherPid, projectName, jobName, contextStr, jobVersion);

		List<String> parametersToEncrypt = new java.util.ArrayList<String>();
        //Resume: jobStart
        resumeUtil.addLog("JOB_STARTED", "JOB:" + jobName, parent_part_launcher, Thread.currentThread().getId() + "", "","","","",resumeUtil.convertToJsonText(context,parametersToEncrypt));

if(execStat) {
    try {
        runStat.openSocket(!isChildJob);
        runStat.setAllPID(rootPid, fatherPid, pid, jobName);
        runStat.startThreadStat(clientHost, portStats);
        runStat.updateStatOnJob(RunStat.JOBSTART, fatherNode);
    } catch (java.io.IOException ioException) {
        ioException.printStackTrace();
    }
}



	
	    java.util.concurrent.ConcurrentHashMap<Object, Object> concurrentHashMap = new java.util.concurrent.ConcurrentHashMap<Object, Object>();
	    globalMap.put("concurrentHashMap", concurrentHashMap);
	

    long startUsedMemory = Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory();
    long endUsedMemory = 0;
    long end = 0;

    startTime = System.currentTimeMillis();




this.globalResumeTicket = true;//to run tPreJob




this.globalResumeTicket = false;//to run others jobs

try {
errorCode = null;tRESTClient_2Process(globalMap);
if(!"failure".equals(status)) { status = "end"; }
}catch (TalendException e_tRESTClient_2) {
globalMap.put("tRESTClient_2_SUBPROCESS_STATE", -1);

e_tRESTClient_2.printStackTrace();

}

this.globalResumeTicket = true;//to run tPostJob




        end = System.currentTimeMillis();

        if (watch) {
            System.out.println((end-startTime)+" milliseconds");
        }

        endUsedMemory = Runtime.getRuntime().totalMemory() - Runtime.getRuntime().freeMemory();
        if (false) {
            System.out.println((endUsedMemory - startUsedMemory) + " bytes memory increase when running : xchange_api_consume");
        }



if (execStat) {
    runStat.updateStatOnJob(RunStat.JOBEND, fatherNode);
    runStat.stopThreadStat();
}
    int returnCode = 0;
    if(errorCode == null) {
         returnCode = status != null && status.equals("failure") ? 1 : 0;
    } else {
         returnCode = errorCode.intValue();
    }
    resumeUtil.addLog("JOB_ENDED", "JOB:" + jobName, parent_part_launcher, Thread.currentThread().getId() + "", "","" + returnCode,"","","");

    return returnCode;

  }

    // only for OSGi env
    public void destroy() {


    }














    private java.util.Map<String, Object> getSharedConnections4REST() {
        java.util.Map<String, Object> connections = new java.util.HashMap<String, Object>();







        return connections;
    }

    private void evalParam(String arg) {
        if (arg.startsWith("--resuming_logs_dir_path")) {
            resuming_logs_dir_path = arg.substring(25);
        } else if (arg.startsWith("--resuming_checkpoint_path")) {
            resuming_checkpoint_path = arg.substring(27);
        } else if (arg.startsWith("--parent_part_launcher")) {
            parent_part_launcher = arg.substring(23);
        } else if (arg.startsWith("--watch")) {
            watch = true;
        } else if (arg.startsWith("--stat_port=")) {
            String portStatsStr = arg.substring(12);
            if (portStatsStr != null && !portStatsStr.equals("null")) {
                portStats = Integer.parseInt(portStatsStr);
            }
        } else if (arg.startsWith("--trace_port=")) {
            portTraces = Integer.parseInt(arg.substring(13));
        } else if (arg.startsWith("--client_host=")) {
            clientHost = arg.substring(14);
        } else if (arg.startsWith("--context=")) {
            contextStr = arg.substring(10);
            isDefaultContext = false;
        } else if (arg.startsWith("--father_pid=")) {
            fatherPid = arg.substring(13);
        } else if (arg.startsWith("--root_pid=")) {
            rootPid = arg.substring(11);
        } else if (arg.startsWith("--father_node=")) {
            fatherNode = arg.substring(14);
        } else if (arg.startsWith("--pid=")) {
            pid = arg.substring(6);
        } else if (arg.startsWith("--context_type")) {
            String keyValue = arg.substring(15);
			int index = -1;
            if (keyValue != null && (index = keyValue.indexOf('=')) > -1) {
                if (fatherPid==null) {
                    context_param.setContextType(keyValue.substring(0, index), replaceEscapeChars(keyValue.substring(index + 1)));
                } else { // the subjob won't escape the especial chars
                    context_param.setContextType(keyValue.substring(0, index), keyValue.substring(index + 1) );
                }

            }

		} else if (arg.startsWith("--context_param")) {
            String keyValue = arg.substring(16);
            int index = -1;
            if (keyValue != null && (index = keyValue.indexOf('=')) > -1) {
                if (fatherPid==null) {
                    context_param.put(keyValue.substring(0, index), replaceEscapeChars(keyValue.substring(index + 1)));
                } else { // the subjob won't escape the especial chars
                    context_param.put(keyValue.substring(0, index), keyValue.substring(index + 1) );
                }
            }
        }else if (arg.startsWith("--log4jLevel=")) {
            log4jLevel = arg.substring(13);
		}

    }
    
    private static final String NULL_VALUE_EXPRESSION_IN_COMMAND_STRING_FOR_CHILD_JOB_ONLY = "<TALEND_NULL>";

    private final String[][] escapeChars = {
        {"\\\\","\\"},{"\\n","\n"},{"\\'","\'"},{"\\r","\r"},
        {"\\f","\f"},{"\\b","\b"},{"\\t","\t"}
        };
    private String replaceEscapeChars (String keyValue) {

		if (keyValue == null || ("").equals(keyValue.trim())) {
			return keyValue;
		}

		StringBuilder result = new StringBuilder();
		int currIndex = 0;
		while (currIndex < keyValue.length()) {
			int index = -1;
			// judege if the left string includes escape chars
			for (String[] strArray : escapeChars) {
				index = keyValue.indexOf(strArray[0],currIndex);
				if (index>=0) {

					result.append(keyValue.substring(currIndex, index + strArray[0].length()).replace(strArray[0], strArray[1]));
					currIndex = index + strArray[0].length();
					break;
				}
			}
			// if the left string doesn't include escape chars, append the left into the result
			if (index < 0) {
				result.append(keyValue.substring(currIndex));
				currIndex = currIndex + keyValue.length();
			}
		}

		return result.toString();
    }

    public Integer getErrorCode() {
        return errorCode;
    }


    public String getStatus() {
        return status;
    }

    ResumeUtil resumeUtil = null;
}
/************************************************************************************************
 *     81903 characters generated by Talend Open Studio for Data Integration 
 *     on the 7 de mayo de 2018 09:52:29 PM COT
 ************************************************************************************************/