# Generated by Django 2.0.4 on 2018-05-07 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('accion', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.FileField(upload_to='')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dimcontraparte',
            fields=[
                ('idcontraparte', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'dimcontraparte',
            },
        ),
        migrations.CreateModel(
            name='Dimestado',
            fields=[
                ('idestado', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'dimestado',
            },
        ),
        migrations.CreateModel(
            name='Dimfecha',
            fields=[
                ('idfecha', models.CharField(db_column='idFecha', max_length=50, primary_key=True, serialize=False)),
                ('anio', models.SmallIntegerField()),
                ('mes', models.SmallIntegerField()),
                ('nombre_mes', models.CharField(db_column='nombre_Mes', max_length=50)),
                ('dia', models.SmallIntegerField()),
                ('nombre_dia', models.CharField(db_column='nombre_Dia', max_length=50)),
            ],
            options={
                'db_table': 'dimfecha',
            },
        ),
        migrations.CreateModel(
            name='Diminfomoneda',
            fields=[
                ('idmoneda', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'diminfomoneda',
            },
        ),
        migrations.CreateModel(
            name='Dimportafolio',
            fields=[
                ('idportafolio', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'dimportafolio',
            },
        ),
        migrations.CreateModel(
            name='Dimproducto',
            fields=[
                ('idproducto', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_operacion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dimproducto',
            },
        ),
        migrations.CreateModel(
            name='Dimsistema',
            fields=[
                ('idsistema', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'dimsistema',
            },
        ),
        migrations.CreateModel(
            name='Dimtrader',
            fields=[
                ('idtrader', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'dimtrader',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('mensaje', models.CharField(max_length=200)),
            ],
        ),
    ]
