# Generated by Django 2.0.4 on 2018-05-04 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.FileField(upload_to='')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dimcontraparte',
            fields=[
                ('idcontraparte', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'dimcontraparte',
            },
        ),
        migrations.CreateModel(
            name='Dimestado',
            fields=[
                ('idestado', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'dimestado',
            },
        ),
        migrations.CreateModel(
            name='Dimfecha',
            fields=[
                ('idfecha', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('anio', models.CharField(blank=True, max_length=20, null=True)),
                ('mes', models.CharField(blank=True, max_length=20, null=True)),
                ('dia', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_mes', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_dia', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'dimfecha',
            },
        ),
        migrations.CreateModel(
            name='Diminfomoneda',
            fields=[
                ('idmoneda', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'diminfomoneda',
            },
        ),
        migrations.CreateModel(
            name='Dimportafolio',
            fields=[
                ('idportafolio', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=15, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'dimportafolio',
            },
        ),
        migrations.CreateModel(
            name='Dimproducto',
            fields=[
                ('idproducto', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_operacion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'dimproducto',
            },
        ),
        migrations.CreateModel(
            name='Dimsistema',
            fields=[
                ('idsistema', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'dimsistema',
            },
        ),
        migrations.CreateModel(
            name='Dimtrader',
            fields=[
                ('idtrader', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('apellido', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'dimtrader',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('mensaje', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Operaciones',
            fields=[
                ('idoperacion', models.CharField(db_column='idOperacion', max_length=20, primary_key=True, serialize=False)),
                ('contrapartecierre', models.CharField(blank=True, db_column='contraparteCierre', max_length=20, null=True)),
                ('idestado', models.CharField(blank=True, db_column='idEstado', max_length=20, null=True)),
                ('fechacarga', models.CharField(blank=True, db_column='fechaCarga', max_length=50, null=True)),
                ('fechafinalizacion', models.CharField(blank=True, db_column='fechaFinalizacion', max_length=50, null=True)),
                ('fechainsercion', models.CharField(blank=True, db_column='fechaInsercion', max_length=50, null=True)),
                ('fechapago', models.CharField(blank=True, db_column='fechaPago', max_length=50, null=True)),
                ('idmonedafuerte', models.CharField(blank=True, db_column='idMonedaFuerte', max_length=20, null=True)),
                ('idmonedadebil', models.CharField(blank=True, db_column='idMonedaDebil', max_length=20, null=True)),
                ('idportafolio', models.CharField(blank=True, db_column='idPortafolio', max_length=20, null=True)),
                ('idproducto', models.CharField(blank=True, db_column='idProducto', max_length=20, null=True)),
                ('idsistema', models.CharField(blank=True, db_column='idSistema', max_length=20, null=True)),
                ('idtrader', models.CharField(blank=True, db_column='idTrader', max_length=20, null=True)),
                ('cant_contratos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'operaciones',
            },
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
