# Generated by Django 2.0.4 on 2018-05-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accion',
            name='estado',
            field=models.CharField(default='cargado', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dimportafolio',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
