# Generated by Django 2.0.4 on 2018-04-21 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_serie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Serie',
        ),
    ]
