# Generated by Django 2.0.4 on 2018-05-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180507_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accion',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
