# Generated by Django 2.0.4 on 2018-05-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accion',
            name='accion',
            field=models.CharField(max_length=200),
        ),
    ]
