# Generated by Django 2.0.4 on 2018-05-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180509_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factmoneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('xchange', models.FloatField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=15, null=True)),
                ('m1', models.CharField(blank=True, max_length=5, null=True)),
                ('m2', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'factmoneda',
            },
        ),
    ]
