# Generated by Django 2.0.4 on 2018-04-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='mensaje',
            field=models.FileField(upload_to=''),
        ),
    ]
